on:
  workflow_dispatch:
   inputs:
    appenv:
      type: choice
      description: Choose the target environment
      options: 
        - dev
        - test
        - prod

name: Azure Bicep-Advanced
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
       creds : '${{ secrets.AZURE_CREDENTIALS }}'
       # client-id: ${{ secrets.AZURE_CLIENT_ID }}
       # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       # enable-AzPSSession: true
    

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=${{ github.event.inputs.appenv }}
